
-- Add onboarding fields to profiles table
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS age integer,
  ADD COLUMN IF NOT EXISTS gender text,
  ADD COLUMN IF NOT EXISTS city text,
  ADD COLUMN IF NOT EXISTS education_level text,
  ADD COLUMN IF NOT EXISTS konkur_year integer,
  ADD COLUMN IF NOT EXISTS last_exam_rank integer,
  ADD COLUMN IF NOT EXISTS university_major text,
  ADD COLUMN IF NOT EXISTS current_semester integer,
  ADD COLUMN IF NOT EXISTS current_gpa numeric,
  ADD COLUMN IF NOT EXISTS target_gpa numeric,
  ADD COLUMN IF NOT EXISTS semester_credits integer,
  ADD COLUMN IF NOT EXISTS grade_level text,
  ADD COLUMN IF NOT EXISTS average_grades numeric,
  ADD COLUMN IF NOT EXISTS main_goal text,
  ADD COLUMN IF NOT EXISTS goal_timeline text,
  ADD COLUMN IF NOT EXISTS subject_priorities jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS avg_daily_study_hours numeric,
  ADD COLUMN IF NOT EXISTS plan_adherence integer,
  ADD COLUMN IF NOT EXISTS biggest_challenge text,
  ADD COLUMN IF NOT EXISTS best_study_time text,
  ADD COLUMN IF NOT EXISTS learning_style text,
  ADD COLUMN IF NOT EXISTS study_environment text,
  ADD COLUMN IF NOT EXISTS weekly_schedule jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS fixed_commitments jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS motivation_reason text,
  ADD COLUMN IF NOT EXISTS biggest_fear text,
  ADD COLUMN IF NOT EXISTS planning_experience text,
  ADD COLUMN IF NOT EXISTS preferred_tone text DEFAULT 'friendly',
  ADD COLUMN IF NOT EXISTS color_theme text DEFAULT 'default',
  ADD COLUMN IF NOT EXISTS reminder_intensity text DEFAULT 'medium',
  ADD COLUMN IF NOT EXISTS reminder_type text DEFAULT 'notification',
  ADD COLUMN IF NOT EXISTS onboarding_step integer DEFAULT 0;
